# Generated by Django 3.1.1 on 2020-09-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigBoringBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_updated',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
